/**
 * Readiness Export Utilities
 *
 * Generates plaintext and HTML summaries of inspection readiness status.
 *
 * ⚠️  SECURITY & PII CONSIDERATIONS:
 * - Data shared via Share API includes personal business information (business name, location, profile).
 * - Document details (permit/license numbers, expiry dates) are included.
 * - Recipient device/email is not under app control; assume data persists indefinitely.
 * - Do NOT include: user email, phone, internal user IDs, Firestore paths, or debug info.
 * - Share should be user-initiated only (button tap, not automatic).
 * - Consider adding a confirmation dialog warning user about data being shared.
 * - Future: add option to redact sensitive document details before sharing.
 */

/**
 * Generate plaintext readiness summary for sharing/export
 * @param {Object} dashboardData - Dashboard snapshot data
 * @param {Object} scoreData - Compliance score breakdown
 * @param {Object} businessProfile - Business profile (optional, for context)
 * @returns {string} Plaintext summary
 */
export const generateReadinessPlaintext = (dashboardData, scoreData, businessProfile = {}) => {
  if (!dashboardData || !scoreData) {
    return 'Readiness summary unavailable.';
  }

  const timestamp = new Date().toLocaleString();
  const { business_name = 'Food Truck', state = 'Unknown' } = businessProfile;

  const lines = [
    `INSPECTION READINESS SUMMARY`,
    `Generated: ${timestamp}`,
    `Business: ${business_name} (${state})`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `READINESS SCORE: ${scoreData.score}% - ${scoreData.factors ? (scoreData.score >= 80 ? 'EXCELLENT' : scoreData.score >= 60 ? 'GOOD' : scoreData.score >= 40 ? 'FAIR' : 'LOW') : 'UNKNOWN'}`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `COMPLIANCE BREAKDOWN:`,
    `• Checklist Completion: ${scoreData.checklistCompletion}%`,
    `  (${scoreData.factors?.completedChecklistItems || 0}/${scoreData.factors?.totalChecklistItems || 0} items)`,
    `• Overdue Items: ${scoreData.factors?.overdueCount || 0}`,
    `• Expiring Documents (30 days): ${scoreData.factors?.expiringCount || 0}`,
    `• Expired Documents: ${Math.max(0, (scoreData.factors?.expiredCount || 0))}`,
    `• Recent Evidence: ${scoreData.factors?.recentMediaLogsCount || 0} logs (last 7 days)`,
    ``,
  ];

  if (dashboardData.overdueItems && dashboardData.overdueItems.length > 0) {
    lines.push(`CRITICAL: ${dashboardData.overdueItems.length} OVERDUE ITEM(S)`);
    dashboardData.overdueItems.slice(0, 5).forEach((item) => {
      lines.push(`  - ${item.name || 'Unnamed item'}`);
    });
    if (dashboardData.overdueItems.length > 5) {
      lines.push(`  ... and ${dashboardData.overdueItems.length - 5} more`);
    }
    lines.push(``);
  }

  if (dashboardData.expiredDocuments && dashboardData.expiredDocuments.length > 0) {
    lines.push(`CRITICAL: ${dashboardData.expiredDocuments.length} EXPIRED DOCUMENT(S)`);
    dashboardData.expiredDocuments.slice(0, 5).forEach((doc) => {
      lines.push(`  - ${doc.documentType || 'Document'}: ${doc.expiryDate || 'date unknown'}`);
    });
    if (dashboardData.expiredDocuments.length > 5) {
      lines.push(`  ... and ${dashboardData.expiredDocuments.length - 5} more`);
    }
    lines.push(``);
  }

  if (dashboardData.expiringDocuments && dashboardData.expiringDocuments.length > 0) {
    lines.push(`WARNING: ${dashboardData.expiringDocuments.length} DOCUMENT(S) EXPIRING SOON`);
    dashboardData.expiringDocuments.slice(0, 5).forEach((doc) => {
      lines.push(`  - ${doc.documentType || 'Document'}: Expires ${doc.expiryDate || 'date unknown'}`);
    });
    if (dashboardData.expiringDocuments.length > 5) {
      lines.push(`  ... and ${dashboardData.expiringDocuments.length - 5} more`);
    }
    lines.push(``);
  }

  lines.push(
    ``,
    `DISCLAIMER:`,
    `This readiness summary is not a legal compliance guarantee. It is a`,
    `snapshot of your documented compliance status only. Please consult`,
    `with local health and safety authorities for definitive compliance`,
    `requirements. This app does not constitute legal advice.`,
    ``,
    `Generated by: Food Truck Compliance App`,
  );

  return lines.join('\n');
};

/**
 * Generate HTML readiness summary for export/email
 * @param {Object} dashboardData - Dashboard snapshot data
 * @param {Object} scoreData - Compliance score breakdown
 * @param {Object} businessProfile - Business profile (optional, for context)
 * @returns {string} HTML string
 */
export const generateReadinessHtml = (dashboardData, scoreData, businessProfile = {}) => {
  if (!dashboardData || !scoreData) {
    return '<p>Readiness summary unavailable.</p>';
  }

  const timestamp = new Date().toLocaleString();
  const { business_name = 'Food Truck', state = 'Unknown' } = businessProfile;

  const scoreColor =
    scoreData.score >= 80 ? '#22c55e' : scoreData.score >= 60 ? '#3b82f6' : scoreData.score >= 40 ? '#f59e0b' : '#ef4444';
  const scoreLabel =
    scoreData.score >= 80 ? 'EXCELLENT' : scoreData.score >= 60 ? 'GOOD' : scoreData.score >= 40 ? 'FAIR' : 'LOW';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Readiness Summary</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #f9fafb;
      padding: 20px;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      overflow: hidden;
    }
    .header {
      background: #1f2937;
      color: white;
      padding: 24px;
      text-align: center;
    }
    .header h1 {
      margin: 0 0 8px 0;
      font-size: 24px;
    }
    .header p {
      margin: 0;
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 24px;
    }
    .business-info {
      background: #f3f4f6;
      border-left: 4px solid #6366f1;
      padding: 12px;
      margin-bottom: 24px;
      border-radius: 4px;
      font-size: 14px;
    }
    .score-card {
      background: ${scoreColor};
      color: white;
      padding: 24px;
      border-radius: 8px;
      margin-bottom: 24px;
      text-align: center;
    }
    .score-card .number {
      font-size: 48px;
      font-weight: bold;
      margin-bottom: 8px;
    }
    .score-card .label {
      font-size: 18px;
      font-weight: 600;
    }
    .section {
      margin-bottom: 24px;
    }
    .section-title {
      font-size: 16px;
      font-weight: 700;
      color: #1f2937;
      margin-bottom: 12px;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 8px;
    }
    .stat-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      font-size: 14px;
      border-bottom: 1px solid #f3f4f6;
    }
    .stat-row:last-child {
      border-bottom: none;
    }
    .stat-label {
      color: #6b7280;
    }
    .stat-value {
      font-weight: 600;
      color: #1f2937;
    }
    .alert {
      padding: 12px;
      border-radius: 6px;
      margin-bottom: 12px;
      font-size: 13px;
      line-height: 1.5;
    }
    .alert-critical {
      background: #fee2e2;
      border-left: 4px solid #ef4444;
      color: #7f1d1d;
    }
    .alert-warning {
      background: #fef3c7;
      border-left: 4px solid #f59e0b;
      color: #78350f;
    }
    .alert-item {
      margin: 4px 0;
      padding-left: 16px;
    }
    .disclaimer {
      background: #fef3c7;
      border: 1px solid #fcd34d;
      border-radius: 6px;
      padding: 16px;
      font-size: 12px;
      color: #78350f;
      line-height: 1.5;
      margin-top: 24px;
    }
    .footer {
      background: #f9fafb;
      padding: 16px;
      text-align: center;
      font-size: 12px;
      color: #6b7280;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Inspection Readiness Summary</h1>
      <p>${timestamp}</p>
    </div>
    
    <div class="content">
      <div class="business-info">
        <strong>${business_name}</strong><br>
        ${state}
      </div>
      
      <div class="score-card">
        <div class="number">${scoreData.score}%</div>
        <div class="label">${scoreLabel}</div>
      </div>
      
      <div class="section">
        <div class="section-title">Compliance Breakdown</div>
        <div class="stat-row">
          <span class="stat-label">Checklist Completion</span>
          <span class="stat-value">${scoreData.checklistCompletion}%</span>
        </div>
        <div class="stat-row">
          <span class="stat-label">Completed Items</span>
          <span class="stat-value">${scoreData.factors?.completedChecklistItems || 0}/${scoreData.factors?.totalChecklistItems || 0}</span>
        </div>
        <div class="stat-row">
          <span class="stat-label">Overdue Items</span>
          <span class="stat-value">${scoreData.factors?.overdueCount || 0}</span>
        </div>
        <div class="stat-row">
          <span class="stat-label">Expiring Documents</span>
          <span class="stat-value">${scoreData.factors?.expiringCount || 0}</span>
        </div>
        <div class="stat-row">
          <span class="stat-label">Expired Documents</span>
          <span class="stat-value">${scoreData.factors?.expiredCount || 0}</span>
        </div>
        <div class="stat-row">
          <span class="stat-label">Recent Evidence (7 days)</span>
          <span class="stat-value">${scoreData.factors?.recentMediaLogsCount || 0}</span>
        </div>
      </div>
      
      ${
        dashboardData.overdueItems && dashboardData.overdueItems.length > 0
          ? `
      <div class="section">
        <div class="section-title">Critical: Overdue Items</div>
        ${dashboardData.overdueItems
          .slice(0, 5)
          .map((item) => `<div class="alert alert-critical"><div class="alert-item">${item.name || 'Unnamed item'}</div></div>`)
          .join('')}
        ${dashboardData.overdueItems.length > 5 ? `<div class="alert alert-critical">... and ${dashboardData.overdueItems.length - 5} more</div>` : ''}
      </div>
      `
          : ''
      }
      
      ${
        dashboardData.expiredDocuments && dashboardData.expiredDocuments.length > 0
          ? `
      <div class="section">
        <div class="section-title">Critical: Expired Documents</div>
        ${dashboardData.expiredDocuments
          .slice(0, 5)
          .map((doc) => `<div class="alert alert-critical"><div class="alert-item">${doc.documentType || 'Document'}: ${doc.expiryDate || 'date unknown'}</div></div>`)
          .join('')}
        ${dashboardData.expiredDocuments.length > 5 ? `<div class="alert alert-critical">... and ${dashboardData.expiredDocuments.length - 5} more</div>` : ''}
      </div>
      `
          : ''
      }
      
      ${
        dashboardData.expiringDocuments && dashboardData.expiringDocuments.length > 0
          ? `
      <div class="section">
        <div class="section-title">Warning: Documents Expiring Soon</div>
        ${dashboardData.expiringDocuments
          .slice(0, 5)
          .map((doc) => `<div class="alert alert-warning"><div class="alert-item">${doc.documentType || 'Document'}: Expires ${doc.expiryDate || 'date unknown'}</div></div>`)
          .join('')}
        ${dashboardData.expiringDocuments.length > 5 ? `<div class="alert alert-warning">... and ${dashboardData.expiringDocuments.length - 5} more</div>` : ''}
      </div>
      `
          : ''
      }
      
      <div class="disclaimer">
        <strong>Disclaimer:</strong> This readiness summary is not a legal compliance guarantee. It is a snapshot of your documented compliance status only. Please consult with local health and safety authorities for definitive compliance requirements. This app does not constitute legal advice.
      </div>
    </div>
    
    <div class="footer">
      Generated by Food Truck Compliance App
    </div>
  </div>
</body>
</html>
  `.trim();

  return html;
};

/**
 * Share readiness summary via native share API
 * Supports plaintext and HTML formats
 *
 * ⚠️  SECURITY NOTE:
 * - Share API sends data to user-selected recipient (email, message, etc.).
 * - Data is not encrypted in transit through user's device apps.
 * - Recipients can forward, screenshot, or print the summary.
 * - Do not share user email, internal IDs, or debug paths.
 * - Always confirm user intent before sharing (button tap, not auto).
 *
 * @param {Object} dashboardData - Dashboard snapshot data
 * @param {Object} scoreData - Compliance score breakdown
 * @param {Object} businessProfile - Business profile
 * @returns {Promise<void>}
 */
export const shareReadinessSummary = async (dashboardData, scoreData, businessProfile = {}) => {
  const { Share } = await import('react-native');

  const plaintext = generateReadinessPlaintext(dashboardData, scoreData, businessProfile);
  const { business_name = 'Food Truck' } = businessProfile;

  try {
    await Share.share({
      message: plaintext,
      title: `${business_name} Readiness Summary`,
      url: undefined, // RN iOS may require this for HTML; we use message instead for text
    });
  } catch (error) {
    console.error('Share failed:', error);
    throw error;
  }
};
